/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as legalRouteRouteImport } from "./routes/(legal)/route";
import { Route as authRouteRouteImport } from "./routes/(auth)/route";
import { Route as appRouteRouteImport } from "./routes/(app)/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as legalTermsRouteImport } from "./routes/(legal)/terms";
import { Route as legalPrivacyRouteImport } from "./routes/(legal)/privacy";
import { Route as authSignupRouteImport } from "./routes/(auth)/signup";
import { Route as authLoginRouteImport } from "./routes/(auth)/login";
import { Route as appSettingsRouteRouteImport } from "./routes/(app)/settings/route";
import { Route as appChatRouteRouteImport } from "./routes/(app)/chat/route";
import { Route as appThreadsIndexRouteImport } from "./routes/(app)/threads/index";
import { Route as appSpacesIndexRouteImport } from "./routes/(app)/spaces/index";
import { Route as appSettingsIndexRouteImport } from "./routes/(app)/settings/index";
import { Route as appLibraryIndexRouteImport } from "./routes/(app)/library/index";
import { Route as appChatIndexRouteImport } from "./routes/(app)/chat/index";
import { Route as appAskIndexRouteImport } from "./routes/(app)/ask/index";
import { Route as ApiRpcSplatRouteImport } from "./routes/api/rpc.$";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth.$";
import { Route as appSettingsBillingRouteImport } from "./routes/(app)/settings/billing";
import { Route as appSettingsAiProvidersRouteImport } from "./routes/(app)/settings/ai-providers";
import { Route as appChatIdRouteImport } from "./routes/(app)/chat/$id";
import { Route as appAdminSlugRouteImport } from "./routes/(app)/admin/$slug";

const legalRouteRoute = legalRouteRouteImport.update({
  id: "/(legal)",
  getParentRoute: () => rootRouteImport,
} as any);
const authRouteRoute = authRouteRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any);
const appRouteRoute = appRouteRouteImport.update({
  id: "/(app)",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const legalTermsRoute = legalTermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => legalRouteRoute,
} as any);
const legalPrivacyRoute = legalPrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => legalRouteRoute,
} as any);
const authSignupRoute = authSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => authRouteRoute,
} as any);
const authLoginRoute = authLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => authRouteRoute,
} as any);
const appSettingsRouteRoute = appSettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => appRouteRoute,
} as any);
const appChatRouteRoute = appChatRouteRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => appRouteRoute,
} as any);
const appThreadsIndexRoute = appThreadsIndexRouteImport.update({
  id: "/threads/",
  path: "/threads/",
  getParentRoute: () => appRouteRoute,
} as any);
const appSpacesIndexRoute = appSpacesIndexRouteImport.update({
  id: "/spaces/",
  path: "/spaces/",
  getParentRoute: () => appRouteRoute,
} as any);
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => appSettingsRouteRoute,
} as any);
const appLibraryIndexRoute = appLibraryIndexRouteImport.update({
  id: "/library/",
  path: "/library/",
  getParentRoute: () => appRouteRoute,
} as any);
const appChatIndexRoute = appChatIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => appChatRouteRoute,
} as any);
const appAskIndexRoute = appAskIndexRouteImport.update({
  id: "/ask/",
  path: "/ask/",
  getParentRoute: () => appRouteRoute,
} as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const appSettingsBillingRoute = appSettingsBillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => appSettingsRouteRoute,
} as any);
const appSettingsAiProvidersRoute = appSettingsAiProvidersRouteImport.update({
  id: "/ai-providers",
  path: "/ai-providers",
  getParentRoute: () => appSettingsRouteRoute,
} as any);
const appChatIdRoute = appChatIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => appChatRouteRoute,
} as any);
const appAdminSlugRoute = appAdminSlugRouteImport.update({
  id: "/admin/$slug",
  path: "/admin/$slug",
  getParentRoute: () => appRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/chat": typeof appChatRouteRouteWithChildren;
  "/settings": typeof appSettingsRouteRouteWithChildren;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
  "/privacy": typeof legalPrivacyRoute;
  "/terms": typeof legalTermsRoute;
  "/admin/$slug": typeof appAdminSlugRoute;
  "/chat/$id": typeof appChatIdRoute;
  "/settings/ai-providers": typeof appSettingsAiProvidersRoute;
  "/settings/billing": typeof appSettingsBillingRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/ask/": typeof appAskIndexRoute;
  "/chat/": typeof appChatIndexRoute;
  "/library/": typeof appLibraryIndexRoute;
  "/settings/": typeof appSettingsIndexRoute;
  "/spaces/": typeof appSpacesIndexRoute;
  "/threads/": typeof appThreadsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
  "/privacy": typeof legalPrivacyRoute;
  "/terms": typeof legalTermsRoute;
  "/admin/$slug": typeof appAdminSlugRoute;
  "/chat/$id": typeof appChatIdRoute;
  "/settings/ai-providers": typeof appSettingsAiProvidersRoute;
  "/settings/billing": typeof appSettingsBillingRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/ask": typeof appAskIndexRoute;
  "/chat": typeof appChatIndexRoute;
  "/library": typeof appLibraryIndexRoute;
  "/settings": typeof appSettingsIndexRoute;
  "/spaces": typeof appSpacesIndexRoute;
  "/threads": typeof appThreadsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/(app)": typeof appRouteRouteWithChildren;
  "/(auth)": typeof authRouteRouteWithChildren;
  "/(legal)": typeof legalRouteRouteWithChildren;
  "/(app)/chat": typeof appChatRouteRouteWithChildren;
  "/(app)/settings": typeof appSettingsRouteRouteWithChildren;
  "/(auth)/login": typeof authLoginRoute;
  "/(auth)/signup": typeof authSignupRoute;
  "/(legal)/privacy": typeof legalPrivacyRoute;
  "/(legal)/terms": typeof legalTermsRoute;
  "/(app)/admin/$slug": typeof appAdminSlugRoute;
  "/(app)/chat/$id": typeof appChatIdRoute;
  "/(app)/settings/ai-providers": typeof appSettingsAiProvidersRoute;
  "/(app)/settings/billing": typeof appSettingsBillingRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/(app)/ask/": typeof appAskIndexRoute;
  "/(app)/chat/": typeof appChatIndexRoute;
  "/(app)/library/": typeof appLibraryIndexRoute;
  "/(app)/settings/": typeof appSettingsIndexRoute;
  "/(app)/spaces/": typeof appSpacesIndexRoute;
  "/(app)/threads/": typeof appThreadsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/chat"
    | "/settings"
    | "/login"
    | "/signup"
    | "/privacy"
    | "/terms"
    | "/admin/$slug"
    | "/chat/$id"
    | "/settings/ai-providers"
    | "/settings/billing"
    | "/api/auth/$"
    | "/api/rpc/$"
    | "/ask/"
    | "/chat/"
    | "/library/"
    | "/settings/"
    | "/spaces/"
    | "/threads/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/signup"
    | "/privacy"
    | "/terms"
    | "/admin/$slug"
    | "/chat/$id"
    | "/settings/ai-providers"
    | "/settings/billing"
    | "/api/auth/$"
    | "/api/rpc/$"
    | "/ask"
    | "/chat"
    | "/library"
    | "/settings"
    | "/spaces"
    | "/threads";
  id:
    | "__root__"
    | "/"
    | "/(app)"
    | "/(auth)"
    | "/(legal)"
    | "/(app)/chat"
    | "/(app)/settings"
    | "/(auth)/login"
    | "/(auth)/signup"
    | "/(legal)/privacy"
    | "/(legal)/terms"
    | "/(app)/admin/$slug"
    | "/(app)/chat/$id"
    | "/(app)/settings/ai-providers"
    | "/(app)/settings/billing"
    | "/api/auth/$"
    | "/api/rpc/$"
    | "/(app)/ask/"
    | "/(app)/chat/"
    | "/(app)/library/"
    | "/(app)/settings/"
    | "/(app)/spaces/"
    | "/(app)/threads/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  appRouteRoute: typeof appRouteRouteWithChildren;
  authRouteRoute: typeof authRouteRouteWithChildren;
  legalRouteRoute: typeof legalRouteRouteWithChildren;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(legal)": {
      id: "/(legal)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof legalRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)": {
      id: "/(auth)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof authRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(app)": {
      id: "/(app)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof appRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(legal)/terms": {
      id: "/(legal)/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof legalTermsRouteImport;
      parentRoute: typeof legalRouteRoute;
    };
    "/(legal)/privacy": {
      id: "/(legal)/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof legalPrivacyRouteImport;
      parentRoute: typeof legalRouteRoute;
    };
    "/(auth)/signup": {
      id: "/(auth)/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof authSignupRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/(auth)/login": {
      id: "/(auth)/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof authLoginRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/(app)/settings": {
      id: "/(app)/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof appSettingsRouteRouteImport;
      parentRoute: typeof appRouteRoute;
    };
    "/(app)/chat": {
      id: "/(app)/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof appChatRouteRouteImport;
      parentRoute: typeof appRouteRoute;
    };
    "/(app)/threads/": {
      id: "/(app)/threads/";
      path: "/threads";
      fullPath: "/threads/";
      preLoaderRoute: typeof appThreadsIndexRouteImport;
      parentRoute: typeof appRouteRoute;
    };
    "/(app)/spaces/": {
      id: "/(app)/spaces/";
      path: "/spaces";
      fullPath: "/spaces/";
      preLoaderRoute: typeof appSpacesIndexRouteImport;
      parentRoute: typeof appRouteRoute;
    };
    "/(app)/settings/": {
      id: "/(app)/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof appSettingsIndexRouteImport;
      parentRoute: typeof appSettingsRouteRoute;
    };
    "/(app)/library/": {
      id: "/(app)/library/";
      path: "/library";
      fullPath: "/library/";
      preLoaderRoute: typeof appLibraryIndexRouteImport;
      parentRoute: typeof appRouteRoute;
    };
    "/(app)/chat/": {
      id: "/(app)/chat/";
      path: "/";
      fullPath: "/chat/";
      preLoaderRoute: typeof appChatIndexRouteImport;
      parentRoute: typeof appChatRouteRoute;
    };
    "/(app)/ask/": {
      id: "/(app)/ask/";
      path: "/ask";
      fullPath: "/ask/";
      preLoaderRoute: typeof appAskIndexRouteImport;
      parentRoute: typeof appRouteRoute;
    };
    "/api/rpc/$": {
      id: "/api/rpc/$";
      path: "/api/rpc/$";
      fullPath: "/api/rpc/$";
      preLoaderRoute: typeof ApiRpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(app)/settings/billing": {
      id: "/(app)/settings/billing";
      path: "/billing";
      fullPath: "/settings/billing";
      preLoaderRoute: typeof appSettingsBillingRouteImport;
      parentRoute: typeof appSettingsRouteRoute;
    };
    "/(app)/settings/ai-providers": {
      id: "/(app)/settings/ai-providers";
      path: "/ai-providers";
      fullPath: "/settings/ai-providers";
      preLoaderRoute: typeof appSettingsAiProvidersRouteImport;
      parentRoute: typeof appSettingsRouteRoute;
    };
    "/(app)/chat/$id": {
      id: "/(app)/chat/$id";
      path: "/$id";
      fullPath: "/chat/$id";
      preLoaderRoute: typeof appChatIdRouteImport;
      parentRoute: typeof appChatRouteRoute;
    };
    "/(app)/admin/$slug": {
      id: "/(app)/admin/$slug";
      path: "/admin/$slug";
      fullPath: "/admin/$slug";
      preLoaderRoute: typeof appAdminSlugRouteImport;
      parentRoute: typeof appRouteRoute;
    };
  }
}

interface appChatRouteRouteChildren {
  appChatIdRoute: typeof appChatIdRoute;
  appChatIndexRoute: typeof appChatIndexRoute;
}

const appChatRouteRouteChildren: appChatRouteRouteChildren = {
  appChatIdRoute: appChatIdRoute,
  appChatIndexRoute: appChatIndexRoute,
};

const appChatRouteRouteWithChildren = appChatRouteRoute._addFileChildren(appChatRouteRouteChildren);

interface appSettingsRouteRouteChildren {
  appSettingsAiProvidersRoute: typeof appSettingsAiProvidersRoute;
  appSettingsBillingRoute: typeof appSettingsBillingRoute;
  appSettingsIndexRoute: typeof appSettingsIndexRoute;
}

const appSettingsRouteRouteChildren: appSettingsRouteRouteChildren = {
  appSettingsAiProvidersRoute: appSettingsAiProvidersRoute,
  appSettingsBillingRoute: appSettingsBillingRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
};

const appSettingsRouteRouteWithChildren = appSettingsRouteRoute._addFileChildren(
  appSettingsRouteRouteChildren,
);

interface appRouteRouteChildren {
  appChatRouteRoute: typeof appChatRouteRouteWithChildren;
  appSettingsRouteRoute: typeof appSettingsRouteRouteWithChildren;
  appAdminSlugRoute: typeof appAdminSlugRoute;
  appAskIndexRoute: typeof appAskIndexRoute;
  appLibraryIndexRoute: typeof appLibraryIndexRoute;
  appSpacesIndexRoute: typeof appSpacesIndexRoute;
  appThreadsIndexRoute: typeof appThreadsIndexRoute;
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appChatRouteRoute: appChatRouteRouteWithChildren,
  appSettingsRouteRoute: appSettingsRouteRouteWithChildren,
  appAdminSlugRoute: appAdminSlugRoute,
  appAskIndexRoute: appAskIndexRoute,
  appLibraryIndexRoute: appLibraryIndexRoute,
  appSpacesIndexRoute: appSpacesIndexRoute,
  appThreadsIndexRoute: appThreadsIndexRoute,
};

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(appRouteRouteChildren);

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute;
  authSignupRoute: typeof authSignupRoute;
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
};

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(authRouteRouteChildren);

interface legalRouteRouteChildren {
  legalPrivacyRoute: typeof legalPrivacyRoute;
  legalTermsRoute: typeof legalTermsRoute;
}

const legalRouteRouteChildren: legalRouteRouteChildren = {
  legalPrivacyRoute: legalPrivacyRoute,
  legalTermsRoute: legalTermsRoute,
};

const legalRouteRouteWithChildren = legalRouteRoute._addFileChildren(legalRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  legalRouteRoute: legalRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
