/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as RobotsDottxtRouteImport } from "./routes/robots[.]txt";
import { Route as DocsRouteRouteImport } from "./routes/docs/route";
import { Route as legalRouteRouteImport } from "./routes/(legal)/route";
import { Route as homeRouteRouteImport } from "./routes/(home)/route";
import { Route as authRouteRouteImport } from "./routes/(auth)/route";
import { Route as appRouteRouteImport } from "./routes/(app)/route";
import { Route as ApiIndexRouteImport } from "./routes/api/index";
import { Route as homeIndexRouteImport } from "./routes/(home)/index";
import { Route as DocsSplatRouteImport } from "./routes/docs/$";
import { Route as ApiSearchRouteImport } from "./routes/api/search";
import { Route as ApiHelloRouteImport } from "./routes/api/hello";
import { Route as ApiHealthRouteImport } from "./routes/api/health";
import { Route as legalTermsRouteImport } from "./routes/(legal)/terms";
import { Route as legalPrivacyRouteImport } from "./routes/(legal)/privacy";
import { Route as homeOpenSourceRouteImport } from "./routes/(home)/open-source";
import { Route as homeDownloadRouteImport } from "./routes/(home)/download";
import { Route as authSignupRouteImport } from "./routes/(auth)/signup";
import { Route as authLoginRouteImport } from "./routes/(auth)/login";
import { Route as appOrpcUsersRouteImport } from "./routes/(app)/orpc-users";
import { Route as appDashboardRouteImport } from "./routes/(app)/dashboard";
import { Route as appSettingsRouteRouteImport } from "./routes/(app)/settings/route";
import { Route as appChatRouteRouteImport } from "./routes/(app)/chat/route";
import { Route as appSettingsIndexRouteImport } from "./routes/(app)/settings/index";
import { Route as appChatIndexRouteImport } from "./routes/(app)/chat/index";
import { Route as ApiWebhooksStripeRouteImport } from "./routes/api/webhooks/stripe";
import { Route as ApiRpcSplatRouteImport } from "./routes/api/rpc.$";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth.$";
import { Route as appSettingsProfileRouteImport } from "./routes/(app)/settings/profile";
import { Route as appSettingsApiKeysRouteImport } from "./routes/(app)/settings/api-keys";
import { Route as appSettingsAiProvidersRouteImport } from "./routes/(app)/settings/ai-providers";
import { Route as appSettingsAiProviderRouteImport } from "./routes/(app)/settings/ai-provider";
import { Route as appSettingsAccountRouteImport } from "./routes/(app)/settings/account";
import { Route as appChatIdRouteImport } from "./routes/(app)/chat/$id";
import { Route as appAdminSlugRouteImport } from "./routes/(app)/admin/$slug";

const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: "/robots.txt",
  path: "/robots.txt",
  getParentRoute: () => rootRouteImport,
} as any);
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: "/docs",
  path: "/docs",
  getParentRoute: () => rootRouteImport,
} as any);
const legalRouteRoute = legalRouteRouteImport.update({
  id: "/(legal)",
  getParentRoute: () => rootRouteImport,
} as any);
const homeRouteRoute = homeRouteRouteImport.update({
  id: "/(home)",
  getParentRoute: () => rootRouteImport,
} as any);
const authRouteRoute = authRouteRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any);
const appRouteRoute = appRouteRouteImport.update({
  id: "/(app)",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: "/api/",
  path: "/api/",
  getParentRoute: () => rootRouteImport,
} as any);
const homeIndexRoute = homeIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => homeRouteRoute,
} as any);
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => DocsRouteRoute,
} as any);
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: "/api/search",
  path: "/api/search",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: "/api/hello",
  path: "/api/hello",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any);
const legalTermsRoute = legalTermsRouteImport.update({
  id: "/terms",
  path: "/terms",
  getParentRoute: () => legalRouteRoute,
} as any);
const legalPrivacyRoute = legalPrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => legalRouteRoute,
} as any);
const homeOpenSourceRoute = homeOpenSourceRouteImport.update({
  id: "/open-source",
  path: "/open-source",
  getParentRoute: () => homeRouteRoute,
} as any);
const homeDownloadRoute = homeDownloadRouteImport.update({
  id: "/download",
  path: "/download",
  getParentRoute: () => homeRouteRoute,
} as any);
const authSignupRoute = authSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => authRouteRoute,
} as any);
const authLoginRoute = authLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => authRouteRoute,
} as any);
const appOrpcUsersRoute = appOrpcUsersRouteImport.update({
  id: "/orpc-users",
  path: "/orpc-users",
  getParentRoute: () => appRouteRoute,
} as any);
const appDashboardRoute = appDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => appRouteRoute,
} as any);
const appSettingsRouteRoute = appSettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => appRouteRoute,
} as any);
const appChatRouteRoute = appChatRouteRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => appRouteRoute,
} as any);
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => appSettingsRouteRoute,
} as any);
const appChatIndexRoute = appChatIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => appChatRouteRoute,
} as any);
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: "/api/webhooks/stripe",
  path: "/api/webhooks/stripe",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: "/api/rpc/$",
  path: "/api/rpc/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const appSettingsProfileRoute = appSettingsProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => appSettingsRouteRoute,
} as any);
const appSettingsApiKeysRoute = appSettingsApiKeysRouteImport.update({
  id: "/api-keys",
  path: "/api-keys",
  getParentRoute: () => appSettingsRouteRoute,
} as any);
const appSettingsAiProvidersRoute = appSettingsAiProvidersRouteImport.update({
  id: "/ai-providers",
  path: "/ai-providers",
  getParentRoute: () => appSettingsRouteRoute,
} as any);
const appSettingsAiProviderRoute = appSettingsAiProviderRouteImport.update({
  id: "/ai-provider",
  path: "/ai-provider",
  getParentRoute: () => appSettingsRouteRoute,
} as any);
const appSettingsAccountRoute = appSettingsAccountRouteImport.update({
  id: "/account",
  path: "/account",
  getParentRoute: () => appSettingsRouteRoute,
} as any);
const appChatIdRoute = appChatIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => appChatRouteRoute,
} as any);
const appAdminSlugRoute = appAdminSlugRouteImport.update({
  id: "/admin/$slug",
  path: "/admin/$slug",
  getParentRoute: () => appRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/docs": typeof DocsRouteRouteWithChildren;
  "/robots.txt": typeof RobotsDottxtRoute;
  "/chat": typeof appChatRouteRouteWithChildren;
  "/settings": typeof appSettingsRouteRouteWithChildren;
  "/dashboard": typeof appDashboardRoute;
  "/orpc-users": typeof appOrpcUsersRoute;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
  "/download": typeof homeDownloadRoute;
  "/open-source": typeof homeOpenSourceRoute;
  "/privacy": typeof legalPrivacyRoute;
  "/terms": typeof legalTermsRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/hello": typeof ApiHelloRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/": typeof homeIndexRoute;
  "/api/": typeof ApiIndexRoute;
  "/admin/$slug": typeof appAdminSlugRoute;
  "/chat/$id": typeof appChatIdRoute;
  "/settings/account": typeof appSettingsAccountRoute;
  "/settings/ai-provider": typeof appSettingsAiProviderRoute;
  "/settings/ai-providers": typeof appSettingsAiProvidersRoute;
  "/settings/api-keys": typeof appSettingsApiKeysRoute;
  "/settings/profile": typeof appSettingsProfileRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/api/webhooks/stripe": typeof ApiWebhooksStripeRoute;
  "/chat/": typeof appChatIndexRoute;
  "/settings/": typeof appSettingsIndexRoute;
}
export interface FileRoutesByTo {
  "/docs": typeof DocsRouteRouteWithChildren;
  "/robots.txt": typeof RobotsDottxtRoute;
  "/dashboard": typeof appDashboardRoute;
  "/orpc-users": typeof appOrpcUsersRoute;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
  "/download": typeof homeDownloadRoute;
  "/open-source": typeof homeOpenSourceRoute;
  "/privacy": typeof legalPrivacyRoute;
  "/terms": typeof legalTermsRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/hello": typeof ApiHelloRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/": typeof homeIndexRoute;
  "/api": typeof ApiIndexRoute;
  "/admin/$slug": typeof appAdminSlugRoute;
  "/chat/$id": typeof appChatIdRoute;
  "/settings/account": typeof appSettingsAccountRoute;
  "/settings/ai-provider": typeof appSettingsAiProviderRoute;
  "/settings/ai-providers": typeof appSettingsAiProvidersRoute;
  "/settings/api-keys": typeof appSettingsApiKeysRoute;
  "/settings/profile": typeof appSettingsProfileRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/api/webhooks/stripe": typeof ApiWebhooksStripeRoute;
  "/chat": typeof appChatIndexRoute;
  "/settings": typeof appSettingsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/(app)": typeof appRouteRouteWithChildren;
  "/(auth)": typeof authRouteRouteWithChildren;
  "/(home)": typeof homeRouteRouteWithChildren;
  "/(legal)": typeof legalRouteRouteWithChildren;
  "/docs": typeof DocsRouteRouteWithChildren;
  "/robots.txt": typeof RobotsDottxtRoute;
  "/(app)/chat": typeof appChatRouteRouteWithChildren;
  "/(app)/settings": typeof appSettingsRouteRouteWithChildren;
  "/(app)/dashboard": typeof appDashboardRoute;
  "/(app)/orpc-users": typeof appOrpcUsersRoute;
  "/(auth)/login": typeof authLoginRoute;
  "/(auth)/signup": typeof authSignupRoute;
  "/(home)/download": typeof homeDownloadRoute;
  "/(home)/open-source": typeof homeOpenSourceRoute;
  "/(legal)/privacy": typeof legalPrivacyRoute;
  "/(legal)/terms": typeof legalTermsRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/hello": typeof ApiHelloRoute;
  "/api/search": typeof ApiSearchRoute;
  "/docs/$": typeof DocsSplatRoute;
  "/(home)/": typeof homeIndexRoute;
  "/api/": typeof ApiIndexRoute;
  "/(app)/admin/$slug": typeof appAdminSlugRoute;
  "/(app)/chat/$id": typeof appChatIdRoute;
  "/(app)/settings/account": typeof appSettingsAccountRoute;
  "/(app)/settings/ai-provider": typeof appSettingsAiProviderRoute;
  "/(app)/settings/ai-providers": typeof appSettingsAiProvidersRoute;
  "/(app)/settings/api-keys": typeof appSettingsApiKeysRoute;
  "/(app)/settings/profile": typeof appSettingsProfileRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/rpc/$": typeof ApiRpcSplatRoute;
  "/api/webhooks/stripe": typeof ApiWebhooksStripeRoute;
  "/(app)/chat/": typeof appChatIndexRoute;
  "/(app)/settings/": typeof appSettingsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/docs"
    | "/robots.txt"
    | "/chat"
    | "/settings"
    | "/dashboard"
    | "/orpc-users"
    | "/login"
    | "/signup"
    | "/download"
    | "/open-source"
    | "/privacy"
    | "/terms"
    | "/api/health"
    | "/api/hello"
    | "/api/search"
    | "/docs/$"
    | "/"
    | "/api/"
    | "/admin/$slug"
    | "/chat/$id"
    | "/settings/account"
    | "/settings/ai-provider"
    | "/settings/ai-providers"
    | "/settings/api-keys"
    | "/settings/profile"
    | "/api/auth/$"
    | "/api/rpc/$"
    | "/api/webhooks/stripe"
    | "/chat/"
    | "/settings/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/docs"
    | "/robots.txt"
    | "/dashboard"
    | "/orpc-users"
    | "/login"
    | "/signup"
    | "/download"
    | "/open-source"
    | "/privacy"
    | "/terms"
    | "/api/health"
    | "/api/hello"
    | "/api/search"
    | "/docs/$"
    | "/"
    | "/api"
    | "/admin/$slug"
    | "/chat/$id"
    | "/settings/account"
    | "/settings/ai-provider"
    | "/settings/ai-providers"
    | "/settings/api-keys"
    | "/settings/profile"
    | "/api/auth/$"
    | "/api/rpc/$"
    | "/api/webhooks/stripe"
    | "/chat"
    | "/settings";
  id:
    | "__root__"
    | "/(app)"
    | "/(auth)"
    | "/(home)"
    | "/(legal)"
    | "/docs"
    | "/robots.txt"
    | "/(app)/chat"
    | "/(app)/settings"
    | "/(app)/dashboard"
    | "/(app)/orpc-users"
    | "/(auth)/login"
    | "/(auth)/signup"
    | "/(home)/download"
    | "/(home)/open-source"
    | "/(legal)/privacy"
    | "/(legal)/terms"
    | "/api/health"
    | "/api/hello"
    | "/api/search"
    | "/docs/$"
    | "/(home)/"
    | "/api/"
    | "/(app)/admin/$slug"
    | "/(app)/chat/$id"
    | "/(app)/settings/account"
    | "/(app)/settings/ai-provider"
    | "/(app)/settings/ai-providers"
    | "/(app)/settings/api-keys"
    | "/(app)/settings/profile"
    | "/api/auth/$"
    | "/api/rpc/$"
    | "/api/webhooks/stripe"
    | "/(app)/chat/"
    | "/(app)/settings/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren;
  authRouteRoute: typeof authRouteRouteWithChildren;
  homeRouteRoute: typeof homeRouteRouteWithChildren;
  legalRouteRoute: typeof legalRouteRouteWithChildren;
  DocsRouteRoute: typeof DocsRouteRouteWithChildren;
  RobotsDottxtRoute: typeof RobotsDottxtRoute;
  ApiHealthRoute: typeof ApiHealthRoute;
  ApiHelloRoute: typeof ApiHelloRoute;
  ApiSearchRoute: typeof ApiSearchRoute;
  ApiIndexRoute: typeof ApiIndexRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/robots.txt": {
      id: "/robots.txt";
      path: "/robots.txt";
      fullPath: "/robots.txt";
      preLoaderRoute: typeof RobotsDottxtRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/docs": {
      id: "/docs";
      path: "/docs";
      fullPath: "/docs";
      preLoaderRoute: typeof DocsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(legal)": {
      id: "/(legal)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof legalRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(home)": {
      id: "/(home)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof homeRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)": {
      id: "/(auth)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof authRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(app)": {
      id: "/(app)";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof appRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/": {
      id: "/api/";
      path: "/api";
      fullPath: "/api/";
      preLoaderRoute: typeof ApiIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(home)/": {
      id: "/(home)/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof homeIndexRouteImport;
      parentRoute: typeof homeRouteRoute;
    };
    "/docs/$": {
      id: "/docs/$";
      path: "/$";
      fullPath: "/docs/$";
      preLoaderRoute: typeof DocsSplatRouteImport;
      parentRoute: typeof DocsRouteRoute;
    };
    "/api/search": {
      id: "/api/search";
      path: "/api/search";
      fullPath: "/api/search";
      preLoaderRoute: typeof ApiSearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/hello": {
      id: "/api/hello";
      path: "/api/hello";
      fullPath: "/api/hello";
      preLoaderRoute: typeof ApiHelloRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(legal)/terms": {
      id: "/(legal)/terms";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof legalTermsRouteImport;
      parentRoute: typeof legalRouteRoute;
    };
    "/(legal)/privacy": {
      id: "/(legal)/privacy";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof legalPrivacyRouteImport;
      parentRoute: typeof legalRouteRoute;
    };
    "/(home)/open-source": {
      id: "/(home)/open-source";
      path: "/open-source";
      fullPath: "/open-source";
      preLoaderRoute: typeof homeOpenSourceRouteImport;
      parentRoute: typeof homeRouteRoute;
    };
    "/(home)/download": {
      id: "/(home)/download";
      path: "/download";
      fullPath: "/download";
      preLoaderRoute: typeof homeDownloadRouteImport;
      parentRoute: typeof homeRouteRoute;
    };
    "/(auth)/signup": {
      id: "/(auth)/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof authSignupRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/(auth)/login": {
      id: "/(auth)/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof authLoginRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/(app)/orpc-users": {
      id: "/(app)/orpc-users";
      path: "/orpc-users";
      fullPath: "/orpc-users";
      preLoaderRoute: typeof appOrpcUsersRouteImport;
      parentRoute: typeof appRouteRoute;
    };
    "/(app)/dashboard": {
      id: "/(app)/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof appDashboardRouteImport;
      parentRoute: typeof appRouteRoute;
    };
    "/(app)/settings": {
      id: "/(app)/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof appSettingsRouteRouteImport;
      parentRoute: typeof appRouteRoute;
    };
    "/(app)/chat": {
      id: "/(app)/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof appChatRouteRouteImport;
      parentRoute: typeof appRouteRoute;
    };
    "/(app)/settings/": {
      id: "/(app)/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof appSettingsIndexRouteImport;
      parentRoute: typeof appSettingsRouteRoute;
    };
    "/(app)/chat/": {
      id: "/(app)/chat/";
      path: "/";
      fullPath: "/chat/";
      preLoaderRoute: typeof appChatIndexRouteImport;
      parentRoute: typeof appChatRouteRoute;
    };
    "/api/webhooks/stripe": {
      id: "/api/webhooks/stripe";
      path: "/api/webhooks/stripe";
      fullPath: "/api/webhooks/stripe";
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/rpc/$": {
      id: "/api/rpc/$";
      path: "/api/rpc/$";
      fullPath: "/api/rpc/$";
      preLoaderRoute: typeof ApiRpcSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(app)/settings/profile": {
      id: "/(app)/settings/profile";
      path: "/profile";
      fullPath: "/settings/profile";
      preLoaderRoute: typeof appSettingsProfileRouteImport;
      parentRoute: typeof appSettingsRouteRoute;
    };
    "/(app)/settings/api-keys": {
      id: "/(app)/settings/api-keys";
      path: "/api-keys";
      fullPath: "/settings/api-keys";
      preLoaderRoute: typeof appSettingsApiKeysRouteImport;
      parentRoute: typeof appSettingsRouteRoute;
    };
    "/(app)/settings/ai-providers": {
      id: "/(app)/settings/ai-providers";
      path: "/ai-providers";
      fullPath: "/settings/ai-providers";
      preLoaderRoute: typeof appSettingsAiProvidersRouteImport;
      parentRoute: typeof appSettingsRouteRoute;
    };
    "/(app)/settings/ai-provider": {
      id: "/(app)/settings/ai-provider";
      path: "/ai-provider";
      fullPath: "/settings/ai-provider";
      preLoaderRoute: typeof appSettingsAiProviderRouteImport;
      parentRoute: typeof appSettingsRouteRoute;
    };
    "/(app)/settings/account": {
      id: "/(app)/settings/account";
      path: "/account";
      fullPath: "/settings/account";
      preLoaderRoute: typeof appSettingsAccountRouteImport;
      parentRoute: typeof appSettingsRouteRoute;
    };
    "/(app)/chat/$id": {
      id: "/(app)/chat/$id";
      path: "/$id";
      fullPath: "/chat/$id";
      preLoaderRoute: typeof appChatIdRouteImport;
      parentRoute: typeof appChatRouteRoute;
    };
    "/(app)/admin/$slug": {
      id: "/(app)/admin/$slug";
      path: "/admin/$slug";
      fullPath: "/admin/$slug";
      preLoaderRoute: typeof appAdminSlugRouteImport;
      parentRoute: typeof appRouteRoute;
    };
  }
}

interface appChatRouteRouteChildren {
  appChatIdRoute: typeof appChatIdRoute;
  appChatIndexRoute: typeof appChatIndexRoute;
}

const appChatRouteRouteChildren: appChatRouteRouteChildren = {
  appChatIdRoute: appChatIdRoute,
  appChatIndexRoute: appChatIndexRoute,
};

const appChatRouteRouteWithChildren = appChatRouteRoute._addFileChildren(appChatRouteRouteChildren);

interface appSettingsRouteRouteChildren {
  appSettingsAccountRoute: typeof appSettingsAccountRoute;
  appSettingsAiProviderRoute: typeof appSettingsAiProviderRoute;
  appSettingsAiProvidersRoute: typeof appSettingsAiProvidersRoute;
  appSettingsApiKeysRoute: typeof appSettingsApiKeysRoute;
  appSettingsProfileRoute: typeof appSettingsProfileRoute;
  appSettingsIndexRoute: typeof appSettingsIndexRoute;
}

const appSettingsRouteRouteChildren: appSettingsRouteRouteChildren = {
  appSettingsAccountRoute: appSettingsAccountRoute,
  appSettingsAiProviderRoute: appSettingsAiProviderRoute,
  appSettingsAiProvidersRoute: appSettingsAiProvidersRoute,
  appSettingsApiKeysRoute: appSettingsApiKeysRoute,
  appSettingsProfileRoute: appSettingsProfileRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
};

const appSettingsRouteRouteWithChildren = appSettingsRouteRoute._addFileChildren(
  appSettingsRouteRouteChildren,
);

interface appRouteRouteChildren {
  appChatRouteRoute: typeof appChatRouteRouteWithChildren;
  appSettingsRouteRoute: typeof appSettingsRouteRouteWithChildren;
  appDashboardRoute: typeof appDashboardRoute;
  appOrpcUsersRoute: typeof appOrpcUsersRoute;
  appAdminSlugRoute: typeof appAdminSlugRoute;
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appChatRouteRoute: appChatRouteRouteWithChildren,
  appSettingsRouteRoute: appSettingsRouteRouteWithChildren,
  appDashboardRoute: appDashboardRoute,
  appOrpcUsersRoute: appOrpcUsersRoute,
  appAdminSlugRoute: appAdminSlugRoute,
};

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(appRouteRouteChildren);

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute;
  authSignupRoute: typeof authSignupRoute;
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
};

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(authRouteRouteChildren);

interface homeRouteRouteChildren {
  homeDownloadRoute: typeof homeDownloadRoute;
  homeOpenSourceRoute: typeof homeOpenSourceRoute;
  homeIndexRoute: typeof homeIndexRoute;
}

const homeRouteRouteChildren: homeRouteRouteChildren = {
  homeDownloadRoute: homeDownloadRoute,
  homeOpenSourceRoute: homeOpenSourceRoute,
  homeIndexRoute: homeIndexRoute,
};

const homeRouteRouteWithChildren = homeRouteRoute._addFileChildren(homeRouteRouteChildren);

interface legalRouteRouteChildren {
  legalPrivacyRoute: typeof legalPrivacyRoute;
  legalTermsRoute: typeof legalTermsRoute;
}

const legalRouteRouteChildren: legalRouteRouteChildren = {
  legalPrivacyRoute: legalPrivacyRoute,
  legalTermsRoute: legalTermsRoute,
};

const legalRouteRouteWithChildren = legalRouteRoute._addFileChildren(legalRouteRouteChildren);

interface DocsRouteRouteChildren {
  DocsSplatRoute: typeof DocsSplatRoute;
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSplatRoute: DocsSplatRoute,
};

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(DocsRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  homeRouteRoute: homeRouteRouteWithChildren,
  legalRouteRoute: legalRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiHelloRoute: ApiHelloRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiIndexRoute: ApiIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
